Algoritmo "Exercicio1"

Var
   numero : vetor[1..5] de inteiro
   contador, contadorl : inteiro


Inicio

   para contador de 1 ate 5 faca

      escreval("Digite um numero: ")
      leia(numero[contador])

   fimpara
   limpatela

   para contador de 1 ate 5 faca
      escreval("Sequencia Normal: ",numero[contador])
   fimpara


   escreval("----------------------")
   para contador de 5 ate 1  passo -1 faca
      escreval("Sequencia invertida: ",numero[contador])
   fimpara


Fimalgoritmo