Algoritmo "Exercicio1"


Var
   raio, calcula: real

//PROCEDIMENTO CALCULA RAIO -----------------------------------------
procedimento calculaRaio (x : real)

inicio
   calcula <- (4/3) * (pi) * (raio* raio * raio)

fimprocedimento
//FIM----------------------------------------------------------------

Inicio

   escreval("Digite o raio:")
   leia(raio)
   calculaRaio(raio)
   escreval("")
   escreval("Resultado do raio: ",calcula:7:2)






Fimalgoritmo